import React from 'react';
import Head from 'next/head';
import styles from '../styles/About.module.scss';

import PageLayout from '../components/PageLayout';
import DynamicMsgBanner from '../components/banners/DynamicMsgBanner';

const journeyMsg = [
  'My name is Erika Lambe and I, until recently, was a full-time student who also worked full-time at Starbucks as a Barista/ Barista Trainer. During this time, I was able to hone my communication skills as well as other skills such as patience, empathy, organization, and improve my method of completing tasks.',
  'Working for such a busy company takes a lot of ability to stay calm during stressful situations and understanding your limits. It helped me understand how to be in tune with myself and know when I need to ask for help and feedback from my peers. Going to school full-time on the side also helped me stay organized and taught me how to do a deep dive on subjects that I didn’t understand, continuously searching for new knowledge and new ideas.',
  'I love when things are continuously changing and are kept new through new research or new understandings. I love to learn new things and find myself growing bored when things get too monotonous, the main reason why I was so interested in design in the first place.',
];

export default function About() {
  return (
    <>
      <Head>
        <title>Eri Lambe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <DynamicMsgBanner message="It's nice to meet you!" />
        <main className={styles.main}>
          <article className={styles.article}>
            <h3>My Journey</h3>
            {journeyMsg.map((paragraph: string) => (
              <React.Fragment key={paragraph}>
                <p>
                  <span>&emsp;</span>
                  {paragraph}
                </p>
                <br />
              </React.Fragment>
            ))}
          </article>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://www.github.com/ddrosario"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by ddrosario
          </a>
        </footer>
      </PageLayout>
    </>
  );
}
