import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import MobileHeader from '../components/MobileHeader';
import HelloBanner from '../components/banners/HelloBanner';
import EgProject from '../components/EgProject';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eri Lambe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileHeader />
      <HelloBanner />
      <main className={styles.main}>
        <EgProject
          projectImg="https://picsum.photos/300/300"
          projectAlt="someimg"
          title="Mirror"
          description="An online fashion retailer site"
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.github.com/ddrosario"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by ddrosario
        </a>
      </footer>
    </div>
  );
}
