import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { GetStaticPathsContext } from 'next';
import styles from '../styles/Home.module.scss';

import PageLayout from '../components/PageLayout';
import HelloBanner from '../components/banners/HelloBanner';
import EgProject from '../components/EgProject';

const egProjectData = [];

export default function Home() {
  return (
    <>
      <Head>
        <title>Eri Lambe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <HelloBanner />
        <main className={styles.main}>
          {egProjectData.map((projectData) => (
            <EgProject
              key={projectData.title}
              projectImg={projectData.projectImg}
              projectAlt={projectData.projectAlt}
              title={projectData.title}
              description={projectData.description}
            />
          ))}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://www.github.com/ddrosario"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by ddrosario
          </a>
        </footer>
      </PageLayout>
    </>
  );
}
